### PR TITLE
added support for map API keys

### PR DESCRIPTION
**Pull request by averynortonsmith**

### CODE REVIEW

**Comment by camilstaps** [comment]
This seems to work fine on my installation, but I suggest two things if this gets merged:

 - Update the documentation, because it now still seems that you have to access the javascript with a ?gmapKey parameter. Instead, you need to create a node with a `data-apikey` attribute.
 - Rename this attribute to `data-ex-apikey`, as everywhere.

**Comment by averynortonsmith** [comment]
Updated the code to support `data-ex-apikey` in addition to `data-apikey` (I think we want to keep the `data-apikey` option open for the future where the map-extension may be usable outside of Exhibit). I'll look into updating the documentation.

**Comment by karger** [comment]
Avery, I think we need one more change before I can merge this.  You've added api keys in the demos that (I think) work on your local site.  But for deployment we need api keys that work on the main www.simile-widgets.org site where those demos are usually hosted.  You'll also want to add a comment in each demo file telling people that they need to replace our map api key with their map api key.

**Comment by averynortonsmith** [comment]
Realized that I only had added an api key in some demos; I've added it to all demos which use the map extension. The api key should be configured work for any domain. What issue are you running into when you try to run the demos on [www.simile-widgets.org](www.simile-widgets.org)?

**Comment by camilstaps** [comment]
Is there anything I can do to speed this up a bit? This is the last thing that prevents my client from deploying a new version of his Exhibit 3 version.

@averynortonsmith it may be that the API key you created has referrer restrictions that prevent it from working on other sites than your own. You can check this at https://console.developers.google.com/apis/credentials (select the project in the left top, then the edit icon next to the key).

**Comment by averynortonsmith** [comment]
Ok, I think I've cleared up the issues with the two demos that weren't working (just silly mistakes, my apologies). Here's the link with the working examples: [http://scripts.mit.edu/~averyn/exhibit/scripted/demos/](http://scripts.mit.edu/~averyn/exhibit/scripted/demos/)

**Comment by karger** [comment]
Avery, I'm still seeing the timeline fail on the presidents exhibit, even on your demo site.  

image

**Comment by averynortonsmith** [comment]
This seems to be an issue with the code which is raising the "No api-key error message", rather than the api-key code itself. The fact that the map is being displayed correctly shows that the Google maps api-key is being delivered correctly, since the map won't load without an api-key. I'm not sure why some examples are raising this error message; I'll have to look into it. However, in terms of function, the code should be working correctly.

**Comment by averynortonsmith** [comment]
^ Presidents example is working now

**Comment by karger** [comment]
This pull is now live on the exhibit HEAD at http://www.simile-widgets.org/exhibit3/examples/other-versions/HEAD

**Comment by camilstaps** [comment]
Thanks very much both!

**Pull request merged**
